name: flutter_ajanuw_router
description: A router used on Flutter and Flutter WEB.
version: 0.3.0
author: Ajanuw <ajanuw1995@gmail.com>
homepage: https://github.com/januwA/flutter_ajanuw_router

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
